baseURL = 'https://raeperd.github.io/'
languageCode = 'en-us'
title = 'raeperd.github.io'
theme = 'paper'

[params]
  color = 'gray'
  github = 'raeperd'
  linkedin = 'raeperd'
  rss = true
  
  avatar = 'https://avatars.githubusercontent.com/u/41039751?v=4'
  name = 'raeperd'
  bio = 'Talk is Cheap'
