on:
  push:
  schedule:
    - cron: '15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: lts/gallium
          cache: npm
      - uses: actions/cache@v2
        with:
          path: ~/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.OS }}-
      - run: mkdir ./lib/content
      - name: Download articles
        uses: raeperd/google-drive-download-action@v1
        with:
          clientSecret: ${{ secrets.CLIENT_SECRET }}
          clientId: ${{ secrets.CLIENT_ID }}
          redirectUri: ${{ secrets.REDIRECT_URI }}
          credential_json: ${{ secrets.CREDENTIAL_JSON }}
          q: "'1pVVyuei5f4sCg5WuCLzuXNj7CZsmDKyX' in parents and (name = 'articles' or name = 'references' or name = 'algorithms')"
          path: "./lib/content"
      - run: npm run test
      - name: build and test
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm run start
      - uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - run: npm run export
      - uses: actions/upload-artifact@v3
        with:
          name: static-pages
          path: |
            out/
            nginx.conf

  deploy-github-page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: static-pages
      - run: touch .nojekyll
      - uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          publish_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN  }}
          force_orphan: true
