name: github pages

on:
  push:
  schedule:
    - cron: '15 * * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/gallium
          cache: npm
      - uses: actions/cache@v2
        with:
          path: ~/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.OS }}-
      - run: npm ci
      - run: mkdir ./lib/content
      - name: Download articles
        uses: raeperd/google-drive-download-action@v1
        with:
          clientSecret: ${{ secrets.CLIENT_SECRET }}
          clientId: ${{ secrets.CLIENT_ID }}
          redirectUri: ${{ secrets.REDIRECT_URI }}
          credential_json: ${{ secrets.CREDENTIAL_JSON }}
          q: "'1pVVyuei5f4sCg5WuCLzuXNj7CZsmDKyX' in parents and (name = 'articles' or name = 'references')"
          path: "./lib/content"
      - run: npm run test
      - uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm run start
      - name: export
        run: |
          npm run export
          touch ./out/.nojekyll
      - uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          publish_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN  }}
          publish_dir: ./out
          force_orphan: true
